### ISSUE TITLE
Not compatible with gl-react-native > 2.42.3

### ISSUE THREAD

**Issue by queenvictoria** [adhbh/rn-sprite#7]
Hi there. I've debugged an issue I've had and aren't able to get this working with `gl-react-native` `2.43.0` or `2.47.0`. I don't have time right now to see why so I've pinned my version below that. Branch here https://github.com/queenvictoria/rn-sprite/tree/pin-version

There have been a couple of releases in the last 10 days that I'll look in to what may have changed when I get a minute.

**Comment by adhbh** [comment]
This issue is fixed.
